### ISSUE TITLE
Add/Open tab to project needs .spin as a file type option

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/propside#259]
We want the user to be able to create all the different the types of libraries that are in the Simple Libraries folder with Simple View.  Some of the Simple Libraries have .spin files that are used for their PASM code.  So, the file type dropdown should have a .spin choice in the Project -> Open Tab to Project and Project -> Add Tab to Project dialogs.  

Also, Project -> Open Tab to Project does make it possible to select a spin file by setting the file type to Any File (*).  However, after double-clicking an existing .spin file, all that happens is an Untitled tab appears and no filename is added to the project manager.  The expected behavior is that the .spin file would be opened into the tab and its file name would be added to the Project Manager's file list.

**Comment by PropGit** [comment]
__jsdenson replied:__  No further plans to support SPIN in Simple IDE

**Comment by PropGit** [comment]
@jsdenson - Right, but we're not trying to support SPIN... we just need to support adding a text file to the project that happens to have a .spin extension.  

We can select "All Files" from the browser window filter and then select and open the .spin file, but SimpleIDE simply doesn't open it nor add it to the project... just leaves us with a blank tab.  We're relegated to manually adding the file to the .side file, and then everything works perfectly in the project in the Simple IDE.  At the least, we're looking for the add-to-project function to not refuse to include (in .side file) and open a text file just because it has a .spin extension.

Otherwise, only us deep developers can add PASM code from Spin objects into a library project.

**Comment by jsdenson** [comment]
I see.

Thanks for clarifying.

I'll evaluate this.


Best Regards,
--Steve

**Comment by PropGit** [comment]
Thanks @jsdenson.

**Comment by PropGit** [comment]
@jsdenson - Have you looked into this one yet?

**Comment by jsdenson** [comment]
Yes, it will be in the next build.

**Comment by PropGit** [comment]
Verified fixed in v1.0.53.
